[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "auth"
version = "0.1.0"
description = "Authentication service for Healthcare Support Portal"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "pydantic>=2.0.0",
    "python-jose[cryptography]>=3.3.0",
    "passlib[bcrypt]>=1.7.4",
    "common",
]

[tool.hatch.build.targets.wheel]
packages = ["src/auth_service"]

[tool.uv.sources]
common = { workspace = true }
