name: test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1-5"
  push:
    branches: [main]
    paths:
      - "python/rag/langgraph-openinference/galileo-langgraph.ipynb"
      - ".github/workflows/notebooks-integration.yaml"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "python/rag/langgraph-openinference/galileo-langgraph.ipynb"
      - ".github/workflows/notebooks-integration.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  GALILEO_API_KEY: ${{ secrets.GALILEO_API_KEY }}
  GALILEO_PROJECT: ${{ secrets.GALILEO_PROJECT }}
  GALILEO_LOGSTREAM: ${{ secrets.GALILEO_LOGSTREAM }}
  GALILEO_OTEL_ENDPOINT: ${{ secrets.GALILEO_OTEL_ENDPOINT }}

jobs:
  run-notebook:
    name: Execute galileo-langgraph.ipynb
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Jupyter runner
        run: |
          python -m pip install --upgrade pip
          pip install \
            nbconvert==7.16.4 \
            nbclient==0.10.0 \
            ipykernel==6.29.5 \
            jupyter_client==8.6.3 \
            pyzmq==26.2.0 \
            tornado==6.4.1 \
            jupyter_core==5.7.2

      - name: Execute notebook
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
        run: |
          NB_PATH="python/rag/langgraph-openinference/galileo-langgraph.ipynb"
          jupyter nbconvert --to notebook --execute --inplace \
            --ExecutePreprocessor.kernel_name=python3 \
            --ExecutePreprocessor.shutdown_kernel=now \
            "$NB_PATH"

      - name: Upload executed notebook (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: galileo-langgraph-executed
          path: python/rag/langgraph-openinference/galileo-langgraph.ipynb
          if-no-files-found: error


