name: test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1-5"
  push:
    branches: [main]
    paths:
      - "python/rag/langgraph-openinference/galileo-langgraph.ipynb"
      - ".github/workflows/notebooks-integration.yaml"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "python/rag/langgraph-openinference/galileo-langgraph.ipynb"
      - ".github/workflows/notebooks-integration.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  GALILEO_API_KEY: ${{ secrets.GALILEO_API_KEY }}
  GALILEO_PROJECT: ${{ secrets.GALILEO_PROJECT }}
  GALILEO_LOGSTREAM: ${{ secrets.GALILEO_LOGSTREAM }}
  GALILEO_OTEL_ENDPOINT: ${{ secrets.GALILEO_OTEL_ENDPOINT }}

jobs:
  run-notebook:
    name: Execute galileo-langgraph.ipynb
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade jupyter ipykernel jupyter-client
          pip install \
            opentelemetry-api opentelemetry-sdk opentelemetry-exporter-otlp opentelemetry-instrumentation \
            openinference-instrumentation-langchain \
            langchain langchain-community langchain-openai langgraph langchain-text-splitters \
            beautifulsoup4 tiktoken

      - name: Execute notebook
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
        run: |
          NB_PATH="python/rag/langgraph-openinference/galileo-langgraph.ipynb"
          jupyter nbconvert --to notebook --execute --inplace \
            --ExecutePreprocessor.kernel_name=python3 \
            --ExecutePreprocessor.shutdown_kernel=graceful \
            "$NB_PATH"


